### ISSUE TITLE
reproduction

### ISSUE THREAD

**Issue by mumumu77** [bar371/GEFF#6] opened 2023-10-10 00:07 UTC
Hi, great work! I cannnot reproduct your prcc result by the following setting. Please teach me～

python Scripts/inference.py "prcc" "CAL" --reid_config ReIDModules/CAL/configs/res50_cels_cal.yaml --dataset_path "prcc" --device "cuda:0" --reid_checkpoint "prcc-checkpoint.pth.tar" --alpha 0 --detection_threshold 0.7

・PRCC Face Module without Enriched Gallery
Computing CMC and mAP  Computing CMC and mAP for the same clothes setting
Results ---------------------------------------------------
top1:28.9% top5:41.4% top10:44.8% top20:50.3% mAP:18.0%
-----------------------------------------------------------
Computing CMC and mAP  Computing CMC and mAP only for clothes changing
Results ---------------------------------------------------
top1:13.8% top5:17.9% top10:19.7% top20:21.2% mAP:8.0%
-----------------------------------------------------------

**Comment by darkushin** [comment] 2023-10-15 15:24
Hi @mumumu77,
Thank you for your interest in our work.
From the results you reported, it seems that you did not use the gallery enrichment process.
Also, you set the value of alpha to 0 (which basically means that the model predicts the identity based on face features only), while in the reported results we set alpha to 0.75.

Please refer to the Colab notebook we published as a reference for the correct usage of the code.

Let us know if you have further questions.

**Comment by bar371** [comment] 2023-11-19 12:50
Dear @mumumu77 , 
Looking into this issue again we found some discrepancy in the way different operating systems sort the PRCC folders. 
The issue is now fixed. Following are the results we received running in Colab with the parameters you described :

![image](https://github.com/bar371/ReFace/assets/31073837/246a9343-938b-43e8-be89-38e4f29212d1)

We thank you for pointing out this issue.

**Closed as completed by bar371** 2023-11-19 12:50 UTC
